src/rmkit/ui/text.cpy
Was getting a compilation error due to a missing declaration in text.cpy:
```
[evan@blackbox rmkit] ARCH=x86 make rmkit.h
mkdir src/build > /dev/null || true
mkdir: cannot create directory ‘src/build’: File exists
cd src/rmkit && make
make[1]: Entering directory '/home/evan/resources/rmkit/src/rmkit'
make compile_x86
make[2]: Entering directory '/home/evan/resources/rmkit/src/rmkit'
okp -sh -ni -for -d ../.rmkit.h_cpp/ -o ../build/rmkit.h rmkit.cpy -- -pthread -lpthread -DRMKIT_BUILD=1 -O0 -g
compile flags: -pthread -lpthread -DRMKIT_BUILD=1 -O0 -g
g++ -c /home/evan/resources/rmkit/src/.rmkit.h_cpp/rmkit.cpp -o /home/evan/resources/rmkit/src/.rmkit.h_cpp/rmkit.o -pthread -lpthread -DRMKIT_BUILD=1 -O0 -g
In file included from /home/evan/resources/rmkit/src/rmkit/ui/pixmap.cpy:3,
from …
```
=> fix missing justify member

src/rmkit/input/input.cpy, src/rmkit/ui/main_loop.cpy
I need a very simple timer, which I could do with a separate thread, but IMO it's a little simpler in this case to think of the timer as another "input". Happy to rethink if you don't like this idea. Code isn't up yet in remarkable_puzzles, but I can put it on a branch later today.
=> Add timeout_ms to ui::MainLoop::read_input()

src/rmkit/fb/fb.cpy
I don't see any obvious immediate harm from having `~FB()` not virtual, but this makes it more natural to use a plain `FB *` pointer without specifying the concrete type.
This should also silence the warning I get trying to delete any FB subclass, e.g. 
```
warning: deleting object of polymorphic class type 'framebuffer::VirtualFB' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
```
=> Make FB destructors virtual

src/nao/nao.sh
This should make opkg in nao use toltecs wget over the built-in/legacy one.
I have not tested it on device yet but did an isolated test of the change. I'm 99% sure that this works. Probably give it a quick test though.
=> [nao] Make opkg (or any other cmd) prefer the bins from `/opt/bin`

src/common.make, src/harmony/app/ui.cpy, src/minesweeper/main.cpy, src/remux/launcher.cpy, src/rmkit/ui/button.cpy, src/rmkit/ui/dialog.cpy, src/rmkit/ui/dropdown.cpy, src/rmkit/ui/keyboard.cpy, src/rmkit/ui/pager.cpy, src/rmkit/ui/style.h, src/rmkit/ui/text.cpy, src/rmkit/ui/text_input.cpy, src/rmkit/ui/widget.cpy, src/sharenote/main.cpy, src/simple/main.cpy
Based on #50 and #51 this adds a `Style` struct to all widgets.
I've left in the concept of defaults, but instead of those being individual static members of the style class (DEFAULT_FS, DEFAULT_JUSTIFY), there's now a default Style, so anything in the Style struct can have a default.
The style system involves three classes:
* `Style` -- a simple struct holding all style information.
* `Stylesheet` -- used to update individual parts of a `Style`.
* `Stylesheet::Inherited` -- a `Stylesheet` used to copy some variables from one `Style` to another.
The approach this PR suggests to managing styles is to create a `Stylesheet` and apply it to widgets as appropriate. Some widgets have default stylesheets (e.g. Button). For instance, suppose you have two different kinds of buttons you might want …
=> Add Style struct

src/rmkit/ui/button.cpy, src/rmkit/ui/scene.cpy, src/rmkit/ui/style.h, src/rmkit/ui/text.cpy, src/rmkit/ui/widget.cpy
Broken up in to separate commits; happy to make separate PRs if one of these is ok but the other needs more discussion.
Valign should be pretty straightforward, although I only implemented it for Text (and by extension, Button). The only odd part is setting y_padding to 0 instead of the default 10 when using a valign other than TOP.
Border might be a little more controversial. I intended to allow any widget to have a border, and the easiest way I could think of to do that was by drawing the border after `render()`, by having `Scene::redraw()` call `render_border()`. IDK if this is getting too complicated, but I was also thinking about adding `background` (color or transparent) as a style, and at that point it might be handy to move the full "render" cycle into Widget instead of Scene, …
=> Add valign and border styles

src/rmkit/ui/style.h
Now that we have valign, I think `justify` belongs in the `alignment` shortcut, not in the `text_style` shortcut. Maybe in the future `text_style` includes things like bold/italic/font_face if we end up wanting those.
=> [ui] remove justify from text_style

src/rmkit/color.h
I was playing around with your code at the end of #67 and it occurred to me that I was accidentally truncating a few bits off of each channel in the conversion to float. I had made an assumption in an earlier iteration of this code that using 30/60/30 for white (instead of 31/63/31) was the way to go, based on https://www.waveshare.com/w/upload/c/c4/E-paper-mode-declaration.pdf, but that turned out to be incorrect.
Just this small change gets us to 64 shades pretty easily. I can still see a tiny bit of banding on the GC16 gradient with dithering applied, but it's barely noticeable.
=> [rmkit] Increase precision of color::to_float

src/rmkit/ui/dialog.cpy
I needed a simpler Dialog for remarkable_puzzles, so here's one idea.
`DialogBase` handles everything common to all dialogs:
* overlay scene
* scene on_hide event
* positioning
* dialog background and border
`Dialog` is responsible for text-based dialog functions:
* title
* content text
* buttons
How I'm using it currently:
```cpp
class SimpleMessageDialog : ui::DialogBase {
public:
ui::Text * textWidget;
SimpleMessageDialog(int w, int h) : ui::DialogBase(0, 0, w, h)
{
textWidget = new ui::Text(0, 0, w, h, "");
textWidget->set_style(ui::Stylesheet()
.justify_center()
.valign_middle()
.font_size(50));
}
void build_dialog()
{
ui::Scene scene = create_scene();
textWidget->x = x;
textWidget->y = y;
scene->add(textWidget);
}
void set_label(std::string label)
{
textWidget->text = label;
}
void …
```
=> [rmkit] Factor DialogBase out from Dialog

src/rmkit/fb/dither.h
I've noticed that some of the remarkable_puzzle animations are super slow, so I've been doing some profiling. `draw_rect` and whichever dithering function I use together take up about 90% of the time according to gprof, so I'm focusing on those :)
One pretty simple optimization is skipping dithering for WHITE and BLACK colors -- the dithering matrices are normalized so that they add or subtract less than 50% of the difference between two colors (so, e.g. in 2-color dithering 0.0 is shifted to between -0.49 and 0.49, which rounds back to 0.0 in all cases).
This change gives me between a 2x and 5x speedup in dithering, depending on how much gray is being drawn:
<details>
<summary>A sample of lightup, which uses a lot of gray:</summary>
```
%   cumulative   self              self     total …
```
=> [fb] optimize dithering for WHITE and BLACK

src/rmkit/defines.h, src/rmkit/fb/stb_text.cpy, src/rmkit/ui/style.h, src/rmkit/ui/text.cpy
I'm working on puzzle help screens, and noticed that MultiText doesn't support multiple consecutive newlines (as a paragraph break for instance). This needed a 2-part approach: (1) a new split fn that doesn't skip whitespace, (2) using a fixed line_height for shifting the y coordinate between lines, since blank lines don't have any characters to measure. The new line_height style lets you scale the computed line height. I went with 1.2 as a default, since that's what css uses. Even with that default though I noticed that paragraphs are much shorter than they were previously, so I'm happy to make the default higher for backwards compatibility.
=> Line height style

src/remux/launcher.cpy, src/rmkit/init.cpy, src/rmkit/input/events.cpy, src/rmkit/input/gestures.cpy, src/rmkit/input/input.cpy, src/rmkit/ui/main_loop.cpy
* remove wonky backwards event coalescing, instead start with prev_ev for all events
* remove MouseEvent, its not applicable since we started using resim
* set `lifted` on TouchEvent when a finger is lifted (TRACKING_ID set to -1)
* add count_fingers() to TouchEvent and use TouchEvent.fingers in gestures.cpy for figuring out how many fingers pressed
=> [rmkit][input] copy old mt slots from previous event

src/rmkit/fb/fb.cpy
This allows saving just a portion of the framebuffer as a png (I'm using this for generating icons).
=> [fb] Add optional x,y,w,h args to save_lodepng

src/rmkit/color.h
I tried this new code w/ my icon generation script and found that the whites weren't quite white. Using the previous algorithm, WHITE turns into 248, 252, 248 (f8fcf8), in the new one it's 255, 255, 255.
=> [rmkit] increase fidelity of to_rgb8

src/rmkit/fb/stb_text.cpy
Mostly adding this for resim builds, but I'm not attached to the idea or the name.
=> [rmkit] Add RMKIT_DEFAULT_FONT env var

src/input_demo/main.cpy, src/rmkit/ui/events.cpy, src/rmkit/ui/widget.cpy, src/rmkit/util/signals.cpy
First draft of drag and long-click events. A couple thoughts:
Naming might be confusing, since there's already a global Gesture class (edit: but then, "gesture" does seem to be the standard term: see for instance Android's [GestureDetector](https://developer.android.com/training/gestures/detector) which has a lot of similarities w/ this approach). Feedback very welcome.
There's some redundancy with `short_click` and `click`, but they mean slightly different things, which is probably confusing. `click` just means "the mouse was down in this widget, and now it's up", but `short_click` means "down and up within a 50-pixel area, and within 0.5 seconds". Those values are configurable of course, but it's a more specific -- maybe too specific -- idea of what "click" means.
I thought about …
=> [rmkit] Add simple Widget gestures

src/lamp/example.in, src/lamp/main.cpy
Syntax:
- Arc: `pen arc start_x start_y end_x end_y start_angle end_angle`
Angles are in degree. Circle drawing function was also modified to use 0-360 degree arc drawing function.
- Bezier:
- `pen bezier start_x start_y control_x control_y end_x end_y` 
- `pen bezier start_x start_y control1_x control1_y control2_x control2_y end_x end_y`
- Rounded rectangle: `pen roundedrectangle start_x start_y end_x end_y radius`
=> [lamp] Add drawing Arc, Bezier curve and Rounded rectangle

src/rmkit/ui/events.cpy
These are exposed in GESTURE_EVENTS, but there wasn't a way to access them from GESTURE_EVENTS_DELEGATE, since it there's an extra level of indirection.
=> [rmkit] Add widget gesture config setters

src/input_demo/main.cpy, src/rmkit/ui/events.cpy
Turns out there are some puzzles that have special behavior for _right_ click and drag, which is what long_press and drag would simulate.
In the original widget gesture PR I made a point to stop processing events after long_press was detected, so we didn't end up with a weird situation like down + timeout + up triggering both long_press and single_click. But there's a fairly straightforward way to get long_press + drag: add a new state (LONG_DOWN) and then allow transitioning from LONG_DOWN -> DRAGGING, but ignore any up events in LONG_DOWN.
=> [rmkit] Allow drag events after long_press

src/lamp/main.cpy
New action sleep defined with
sleep on | off | 1 < <int> < 10000
sleep time is presented in ms
debug message informs user that a long sleep does not mean lamp hangs or crashed
with on | off users can globally switch the sleep command on or off for the following sleep commands
example:
pen line 0 0 100 100
sleep on
sleep 1000
pen line 100 100 200 200
sleep 1000
sleep off
pen line 200 200 300 300
sleep 1000 # this will not be executed
pen line 300 300 400 400
=> Add sleep action

src/rmkit/fb/fb.cpy
I'm working on dealing with ghosting, and the only thing I've gotten to work is using UPDATE_MODE_FULL with WAVEFORM_MODE_GC16. This makes `fb->redraw_screen(true)` use UPDATE_MODE_FULL.
There are three places I could find that would trigger this code path in rmkit currently:
* remux [App::on_suspend()](https://github.com/rmkit-dev/rmkit/blob/8bd470563412b8526eb901da98380b6df846f3ac/src/remux/launcher.cpy#L571)
* remux [AppBackground::render()](https://github.com/rmkit-dev/rmkit/blob/8bd470563412b8526eb901da98380b6df846f3ac/src/remux/launcher.cpy#L125)
* iago [AppBackground::render()](https://github.com/rmkit-dev/rmkit/blob/8bd470563412b8526eb901da98380b6df846f3ac/src/iago/main.cpy#L31)
^^ I don't know enough about how those are supposed to work to say if using UPDATE_MODE_FULL is …
=> [fb] add update_mode option

src/rmkit/ui/dropdown.cpy
Adds a method to automatically calculate the size of a dropdown's options. This is generally only useful for calculating the option width.
=> [ui] Add TextDropdown::autosize_options

src/input_demo/main.cpy, src/rmkit/ui/dropdown.cpy
A specialization of TextDropdown and DropdownButton for simple menus.
* Defaults to DIRECTION::DOWN
* The menu title is static; selections do not replace it
* Offsets options so they appear below the menu (instead of covering it)
* Auto-sizes options before they are shown
This adds a few features to dropdowns in general:
* New function TextDropdown::add_options, which adds options to the
last-added section (or creates a blank section if none exists). This is
a shortcut so you don't have to add a section if you don't need it.
* The option layout is shifted to the left if it would run off the
screen.
=> [ui] Add ui::DropdownMenu

src/rmkit/fb/fb.cpy
I have some pngs with transparency, and if I load them into a 4-channel image, the alpha channel is preserved. This doesn't get us alpha blending, but it at least lets us use the actual alpha channel on the image.
=> [fb] Support bitmaps with an alpha channel

src/iago/main.cpy, src/iago/shapes.cpy, src/rmkit/ui/button.cpy
- Support snapping on a (invisible) 1-10 millimeter grid
When enabled, placement and movement of shapes/handles is restricted to common horizontal/vertical intervals of the 
snapping value.  
- Add settings dialog with the snapping settings
=> Add snapping

src/rmkit/ui/keyboard.cpy
=> Correct capitalized N and M in onscreen keyboard

docs/BUILDING.md
442721aaae759fffde31f56e5d4cdf304fe80cf8 switches to using TARGET instead of ARCH. This updates the documentation to match.
=> Update BUILDING.md to use TARGET instead of ARCH

src/nao/nao.sh
For some reason, looping through `${SCENE[@]}` was returning `1` for lines starting with `[button`
=> Fix repo select in nao

.github/workflows/pr.yml, .github/workflows/stable-release.yml
Also make the scp upload conditional on if the secret is actually set. This way it wont fail on forks.
=> Update github actions to no longer use deprecated features

src/rmkit/init.cpy
The signal handler is set up for SIGTERM, not SIGKILL, as SIGKILL can't be caught by the process.
=> SIGTERM not SIGKILL

.github/workflows/pr.yml, .github/workflows/stable-release.yml, src/remux/launcher.cpy
This gives the threads custom names to easily identify which thread is doing work in tools like htop.
=> Name remux threads

src/rmkit/fb/fb.cpy, src/rmkit/fb/stb_text.cpy
I have *finally* figured out the issues preventing me from using the single-header rmkit across multiple TUs.
There were a few namespace-level global static variables. If such variables are not `extern` or `inline`, each TU will get their own uninitialized copy of the field.
This resulted in a build that throws no warnings at all, but segfaults at runtime when we try to read a null font, or the FB singleton is empty and we get no render.
I've used `extern` instead of `inline` because rmkit's build process complains about inline and there are already other fields with extern and that clever initializer generation. There should be no difference between the two, but inline is only in C++>=17
I think these were the only such fields left in rmkit. My application seems to work fine now with …
=> single-header fixes
